---
title: "Jakob Böhme <br>und <br>Bob Dylan"
author: "Wolf Riepl"
title-slide-attributes: 
  data-background-color: "#D7E6F4"
subtitle: "Eine Geistesverwandtschaft"
format:
  revealjs:
    theme: blood
execute:
  echo: false
  eval: true
  freeze: auto
  warning: false
  message: false
callout-appearance: simple
---

## Böhme und Dylan: Vergleichbar?

::::: {.incremental style="font-size: 2rem"}
:::: columns
::: column

### Jakob Böhme

* lebte 1575 - 1624
* Schuster
* später Garnhändler
* Buchautor

:::

::: column

### Bob Dylan

* geboren 1941
* *"Song and Dance Man"*: Sänger und Songschreiber
* Buchautor, Regisseur und Darsteller in einigen Filmen

:::
::::
:::::


## Warum?

::: incremental

### Ziele des Vortrags

* Neues lernen?
* Freue mich mehr, wenn etwas in Ihnen Resonanz hervorruft
* "Mit dem Herzen hören"
* Will Sie von nichts überzeugen

:::


## Böhme und Dylan: Parallelen?

::: {.incremental style="font-size: 2rem"}

* Inspiration, die über persönliche Vermögen hinausgeht
* Erstaunliche Produktivität
* Beide gelten als schwer verständlich
* Spiritueller Pfad
  + Selbstübergabe an höhere Kraft
  + Der Mensch als Werkzeug dieser Kraft
  + Wiedergeburt des Göttlichen im Menschen
  + Bedingungslose Akzeptanz der Lebensumstände
:::


## Jakob Böhme: Anerkennung

> Im Wasser lebt der Fisch, die Pflanze in der Erden,  
Der Vogel in der Luft, die Sonn im Firmament,  
Der Salamander muß im Feuer erhalten werden,  
Und Gottes Herz ist Jakob Böhmes Element.

Angelus Silesius (1624 - 1677)


## Jakob Böhme: Anerkennung

> Jakob Böhme, der Mann, dessen Schriften alles das gediegen und in einer festen Masse enthalten, was uns seine albernen Nachfolger mit einer bloß scheinbaren Verständlichkeit verdünnt und verdorben übergeben, ist und bleibt einer der ersten Schriftsteller unserer Nation.

Georg Christoph Lichtenberg (1742-1799)


## Jakob Böhme: Anerkennung

> Jakob Böhme ist der erste deutsche Philosoph,  
der Inhalt seines Philosophierens ist echt deutsch.

Georg Wilhelm Friedrich Hegel (1770 - 1831)


## Jakob Böhme: Anerkennung

> Der bedeutendste von diesen allen ist offenbar der spätere Jacob Böhme, dem man unter den Philosophen dieser Periode überhaupt wohl die erste Stelle einräumen könnte. [...]

> Er ist ohne Zweifel der umfassendste, reichhaltigste und mannigfaltigste von allen Mystikern. Er verbreitet sich über alle Teile, die von andern nur einzeln bearbeitet oder ganz unberührt gelassen wurden.

Friedrich Schlegel (1772 - 1829)


## Jakob Böhme: Anerkennung

> Der Schuster Jakob Böhme war ein großer Philosoph!  
Manche Philosophen von Ruf sind nur große Schuster.

Karl Marx (1818 - 1883)


## Jakob Böhme: Anerkennung

> Jakob Böhmes Schriftchen Von der Gnadenwahl möchte ich zu den tiefsten Erleuchtungen der ganzen Christenheit rechnen.

Leopold Ziegler (1881 - 1958)


## Bob Dylan: Relikt der 1960er?

* Wurde ab 1962 als Folk- und Protestsänger bekannt
* Einige Songs aus dieser Zeit:  
  + *Blowin' in the Wind*
  + *The Times They Are A'Changin'*
  + *With God On Our Side*

  
## Bob Dylan: Anerkennung

::: incremental

* **Nobelpreis für Literatur** 2016
* **Oscar** und **Golden Globe** für *Things Have Changed* (Soundtrack zu *Wonderboys* mit Michael Douglas) 2000
* Personen, die sowohl einen Nobelpreis als auch einen Oscar gewannen:
  + **George Bernard Shaw** und **Bob Dylan**
* Personen, die den Nobelpreis, den Oscar, mindestens einen **Grammy**, einen **Golden Globe** und den **Pulitzer-Preis** gewannen: nur Bob Dylan

:::


